Migrate to assembly 1.1.0
mapbox/mr-ui pull request #124
Opened 2021-05-18 21:57 UTC by samanpwbb

This PR introduces the minimum necessary changes in order to support assembly 1.1.0 while maintaining roughly the same visual styles. Some form elements have changed slightly, and many colors have changed slightly.

2021-05-18 21:59 UTC, samanpwbb commented
Draft until we've deployed https://github.com/mapbox/mbx-assembly/pull/54

2021-05-19 13:55 UTC, tristen requested changes

2021-05-19 13:55 UTC, tristen commented on src/components/control-alert/examples/control-alert-example-options.js
> +          className="color-gray-dark color-blue-on-hover "
```suggestion
          className="color-gray-dark color-blue-on-hover"
```

2021-05-19 13:55 UTC, tristen commented on src/components/control-card/examples/control-card-example-options.js
> +          className="color-gray-dark color-blue-on-hover "
```suggestion
          className="color-gray-dark color-blue-on-hover"
```

2021-05-19 13:55 UTC, tristen commented on src/components/control-switch/__tests__/control-switch-test-cases.js
> +    themeControlSwitch: 'switch--red switch--dot-yellow',
🎪

2021-05-19 13:55 UTC, tristen commented on src/components/underline-tabs/underline-tabs.js
> +      const layoutClasses = classnames('', {
```suggestion
      const layoutClasses = classnames({
```

2021-05-19 13:55 UTC, tristen commented on src/docs/components/sidebar.js
> +          <span className="">View on GitHub</span>
```suggestion
         View on GitHub
```

2021-05-20 15:08 UTC, katydecorah commented on src/components/control-checkbox-set/control-checkbox-set.js
> +    themeCheckbox: 'mr6 inline-block checkbox--blue checkbox--s-label '
```suggestion
    themeCheckbox: 'mr6 inline-block checkbox--blue checkbox--s-label'
```

2021-05-20 16:54 UTC, katydecorah reviewed
Looking good so far! I found a few small-ish suggestions.

2021-05-25 23:24 UTC, samanpwbb commented
@tristen / @katydecorah this is ready for another look. Note that I added some commits that introduce some new sections to the docs site - would be great to get some 👁️ on that work too!

<img width="979" alt="Screen Shot 2021-05-25 at 1 25 45 PM" src="https://user-images.githubusercontent.com/108094/119580638-a27f3100-bd75-11eb-9b61-2eda128d74b0.png">

2021-05-26 16:12 UTC, tristen approved these changes
Changes look good to me! Approving to unblock but the layout for the main content is condensing the name column in some places:

<img width="271" alt="Screen Shot 2021-05-26 at 12 10 49 PM" src="https://user-images.githubusercontent.com/61150/119694841-9c439000-be1b-11eb-8508-6f2883dd9ca1.png">

2021-05-26 17:25 UTC, merged