Reinforced password policy for reset password
mapbox/mr-ui pull request #152
Opened 2022-01-06 22:04 UTC by lawsberryPi

Resolve Pentest Vulnerability-2021: Weak Password Policy, Reinforced password rules so that the password must have:
one uppercase letter 
one lowercase letter
one digit
one special character 
at least 8 chars long

2022-01-06 23:59 UTC, hibsy approved these changes

2022-01-07 06:56 UTC, vatolvan commented
This is only UI change, right? 

Are you gonna add the corresponding change to backend side as well?

2022-01-07 07:01 UTC, vatolvan commented on src/components/form/validators/__tests__/validate-password.test.js
> +    'The string should have a minimum of 1 symbol'
This text is not very user friendly, specifically "the string" -> "the password". 

Also, what does a "symbol" mean?  I tried to think how I would resolve if I got this error myself and really have no idea 😂

2022-01-07 07:05 UTC, vatolvan commented on package.json
> +    "password-validator": "^5.2.1",
What do you think about using regex instead of adding a 3rd party librar? The rules seem to be quite simple so the regex should not be too complicated to to

2022-01-07 08:26 UTC, Miroko commented on src/components/form/validators/__tests__/validate-password.test.js
> +    'The string should have a minimum of 1 symbol'
Usually these are called special characters, we could maybe even show an example for the user what a special character means. Probably any other character that is not a number or letter is considered as special character

2022-01-07 08:45 UTC, vatolvan commented on src/components/form/validators/__tests__/validate-password.test.js
> +    'The string should have a minimum of 1 symbol'
Right!

I agree that it should show the accepted symbols / special characters if this check fails. Otherwise its quite hard to fix

2022-01-07 12:35 UTC, lawsberryPi commented on src/components/form/validators/__tests__/validate-password.test.js
> +    'The string should have a minimum of 1 symbol'
that make sense! I will change the message

2022-01-07 12:35 UTC, lawsberryPi commented on package.json
> +    "password-validator": "^5.2.1",
yeah, i can do that too

2022-01-07 19:22 UTC, yseo93 approved these changes

2022-01-08 10:18 UTC, vatolvan commented on src/components/form/validators/__tests__/validate-password.test.js
> +test('invalid missing lowercase letter returns correct error message', () => {
Can you add one test for testing a case when each of the condition fails

2022-01-09 19:47 UTC, vliman commented on src/components/form/validators/validate-password.js
> +    return 'The password must be at least eight characters long';
I'm not sure it's really needed to start the message from `The` article? Maybe just `Password must be at least eight characters long.` would sound better? Also added dot to the end to be consistent with the rest of the messages.

2022-01-09 19:47 UTC, vliman commented on src/components/form/validators/validate-password.js
> +    validationResult += 'The password must have a uppercase letter. \r\n';
`a uppercase` -> `an uppercase`, no?

2022-01-09 19:47 UTC, vliman commented on src/components/form/validators/validate-password.js
> +    validationResult += 'The password must have a punctuation. \r\n';
Wondering whether `punctuation` would be clear for end users? Maybe we should say `special characters` and list all of the acceptable characters in parentheses? In some places I also saw words `metacharacters` or `non word characters` used to describe these type of symbols, but not sure they better than `special characters`.

2022-01-09 19:47 UTC, vliman commented on src/components/form/validators/validate-password.js
> +  return validationResult;
Thinking about that approach and maybe we can do it in a bit different way without strings concatenation? And I do think we need to immediately return if password is less than 8 characters. As a user I'd rather prefer to see all the missed requirements straightaway.
Something like this (taking into account most of my previous comments except the one regarding punctuation)
```
export default function validatePassword(value) {
  if (isEmptyControlValue(value)) return '';

  const validations = [];

  if (value.length < 8) {
    validations.push('Password must be at least eight characters long.');
  }

  if (!/[a-z]/.test(value)) {
    validations.push('Password must have a lowercase letter.)';
  }

  if (!/[A-Z]/.test(value)) {
    validations.push('Password must have an uppercase letter.)';
  }

  if (!/\d/.test(value)) {
    validations.push('The password must have a number.)';
  }

  if (!/\W/.test(value)) {
    validations.push('The password must have a punctuation.)';
  }

  return validations.join('\r\n');
}

```

2022-01-09 19:47 UTC, vliman commented on src/components/form/validators/validate-password.js
> +    validationResult += 'The password must have a punctuation. \r\n';
We also need to think about what special characters we allow. `\W` is equivalent to `[^a-zA-Z0-9_]` - it means if we use `\W` regex, `_` (underscore symbols) will be excluded from check. Maybe it's better to just list all of the acceptable symbols explicitly in regex? Not sure about that though.

2022-01-09 19:47 UTC, vliman commented on src/components/form/validators/__tests__/validate-password.test.js
> +test('invalid missing lowercase letter returns correct error message', () => {
NIT: I noticed that message ends with `returns correct error message`, but the rest of the messages above end with just `returns error`. I think it make sense to make it consistent everywhere.

2022-01-10 14:17 UTC, lawsberryPi commented on src/components/form/validators/validate-password.js
> +    validationResult += 'The password must have a punctuation. \r\n';
how about we allows users to use these special characters ? https://docs.oracle.com/cd/E11223_01/doc.910/e11197/app_special_char.htm#MCMAD416

2022-01-10 14:18 UTC, lawsberryPi commented on src/components/form/validators/validate-password.js
> +  return validationResult;
sure, that would work

2022-01-10 14:24 UTC, lawsberryPi commented on src/components/form/validators/validate-password.js
> +    validationResult += 'The password must have a uppercase letter. \r\n';
Good catch, changing now

2022-01-10 14:47 UTC, lawsberryPi commented on src/components/form/validators/validate-password.js
> +    validationResult += 'The password must have a punctuation. \r\n';
actually I did some research, I think \W should work, I will just modify the error message just incase user don't know what special characters are

2022-01-10 17:37 UTC, vliman commented on src/components/form/validators/validate-password.js
> +    validationResult += 'The password must have a punctuation. \r\n';
Sounds good, thanks!

2022-01-10 20:25 UTC, mbullington requested changes
Approved on my end after the other comments are resolved. Just make sure to update the package lock to `2.0.0-beta.2` as well before publishing, otherwise it'll just overwrite beta 1.

Thanks for the tag!

2022-01-11 14:42 UTC, vatolvan commented on src/components/form/validators/validate-password.js
> +import React from 'react';
While technically allowed, you are now outputting JSX from pure javascript function. 

You should use the pure javascript functions to output javascript objects / data types and wrap them in JSX in your actual JSX render components / functions.

2022-01-11 14:44 UTC, vatolvan commented on src/components/form/validators/validate-password.js
> +import React from 'react';
So instead of wrapping the list to JSX here in this component, this component should do only whats necessary. Perhaps only generate the array of validation error messages which can then be used as fit from outside this function

2022-01-11 14:46 UTC, vatolvan commented on src/components/form/validators/validate-password.js
> +import React from 'react';
Checked the file and seems we are using the `.js` extension for everything :(

Perhaps this is ok then...

2022-01-11 14:47 UTC, vatolvan commented on src/components/form/validators/validate-password.js
> +import React from 'react';
I would still perhaps just return a list here and use that list / array in the caller component/function

2022-01-11 15:02 UTC, lawsberryPi commented on src/components/form/validators/validate-password.js
> +import React from 'react';
the caller is here, I feel this block of code has much more people use it, so I don't want to change it... I feel it more responsibility to change this part of code         [typeof validationError === 'string'](https://github.com/mapbox/mr-ui/blob/c62882528c3aca00c06526dbcb444eb519b72bf6/src/components/control-wrapper/control-wrapper.js#L31)

2022-01-11 16:38 UTC, vatolvan commented on src/components/form/validators/validate-password.js
> +import React from 'react';
Discussed this in Slack with @lawsberryPi  and its quite a big change to refactor this to return lists in the scope of this PR so this is ok 👍

2022-01-11 17:47 UTC, vliman commented on src/components/form/validators/validate-password.js
> +import React from 'react';
Can I get more clarity here, please? Previously it was a function returning string, now we are making it returning either string or markup. Can I also get examples where that function is being used?

2022-01-11 18:01 UTC, vliman commented
@lawsberryPi I think you also need to update [README](https://github.com/mapbox/mr-ui/blob/main/src/components/form/validators/README.md#validate-password) to reflect latest changes.

2022-01-11 18:05 UTC, vliman commented on src/components/form/validators/validate-password.js
> +import React from 'react';
ok, found this [example](https://github.com/mapbox/mr-ui/blob/main/src/components/form/validators/examples/util-validators-basic.js#L94-L97). If I understood it correctly ControlText component has a property called [validationError](https://github.com/mapbox/mr-ui/blob/main/src/components/control-text/control-text.js#L57) which is of type `PropTypes.node`. So we should be fine here.

2022-01-11 19:08 UTC, merged