Rewrite Popover, drop popover trigger
mapbox/mr-ui pull request #184
Opened 2022-08-03 15:01 UTC by tristen

This PR rewrites `src/components/popover` as a functional, typescript component and uses [`PopoverPrimitive ` from Radix](https://www.radix-ui.com/docs/primitives/components/popover#custom-apis). 

🚨 **Breaking changes**:
- Dropped the separate uncontrolled PopoverTrigger component in favor of composition and promoting controlled implementations.
- `popover` prop changes**:
  - Dropped `getAnchorElement` in favour of an exported PopoverTrigger component instead which Radix encourages

---

Closes #173

2022-08-09 16:28 UTC, tristen commented
I'm running into a similar issue with tests as [reported here](https://github.com/radix-ui/primitives/issues/1608) so I'm going to pause on this work for a bit.

2022-08-10 09:07 UTC, andy-hook commented
> I'm running into a similar issue with tests as [reported here](https://github.com/radix-ui/primitives/issues/1608) so I'm going to pause on this work for a bit.

Hey @tristen I posted a follow up [here](https://github.com/radix-ui/primitives/issues/1608#issuecomment-1210381690) if it's helpful.

2022-08-15 08:46 UTC, miafan23 requested changes
Looks great!
Some changes to the document are required and I'll paste a few videos about some affected UI that I am not able to get the reasons from the code.

2022-08-15 08:46 UTC, miafan23 commented on src/components/copiable/copiable.test.js
> +    */
Maybe add some comments to explain why those test code is commented out? Then when we are rewriting `copiable` component, we'll be more confident to uncomment them or remove them.

2022-08-15 08:46 UTC, miafan23 commented on src/components/popover/popover.tsx
> +    }
```suggestion
    if (typeof content === 'function') {
      return content();
    }
    return content;
```
The `else` seems unnecessary here

2022-08-15 08:46 UTC, miafan23 commented on src/components/popover/popover.tsx
> +   * The trigger eleemnt.
A typo :stuck_out_tongue_closed_eyes:

2022-08-15 08:46 UTC, miafan23 commented on src/components/popover/popover.tsx
> +  /**
Extra comment starter

2022-08-15 08:46 UTC, miafan23 commented on src/components/popover/popover.tsx
> +   */
Missing document for `active` prop

2022-08-15 08:52 UTC, miafan23 commented
The button flashes when you click it. And the content of popover flashes in the last example. I checked the original mr-ui and radix UI official examples, seems both of them don't have this issue.



https://user-images.githubusercontent.com/9078950/184605886-f069cece-cf45-4f91-8574-0c6aa067c30c.mp4

2022-08-15 08:56 UTC, miafan23 commented
Since you touched `copyButton` component, so I also took a look for its example page and found the height of the wrapper changes when you click the copyButton.

https://user-images.githubusercontent.com/9078950/184606429-dd6d1e4c-8762-4903-85b6-773eb8b41e23.mp4

2022-08-15 18:32 UTC, tristen commented on src/components/copiable/copiable.test.js
> +    */
👍 These were re-written in https://github.com/mapbox/mr-ui/pull/186

2022-08-15 18:39 UTC, tristen commented on src/components/popover/popover.tsx
> +   */
Ah! good catch

2022-08-28 13:57 UTC, tristen commented
@miafan23 this is ready for another review!

2022-08-29 07:24 UTC, miafan23 approved these changes
Excellent!

2022-08-29 13:17 UTC, merged