Rewrite non-radix components
mapbox/mr-ui pull request #186
Opened 2022-08-10 14:02 UTC by tristen

Closes #185

2022-08-16 08:30 UTC, miafan23 requested changes
Amazing work! So many changes! :rocket:
There are a few eslint warnings that I think should be cleared.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/9078950/184834452-bcc0fb5d-28d0-428b-9923-67efb6c87d46.png">

2022-08-16 08:30 UTC, miafan23 commented on src/components/utils/omit.ts
> -  source: { [key: string]: PropertyValues } = {},
Could you explain a little bit about why this is removed? Just curious about it.

2022-08-16 08:30 UTC, miafan23 commented on src/components/form/validators/validate-date.ts
> +export default function validateDate(value: any) {
```suggestion
export default function validateDate(value: any):string {
```
Maybe add a return type like all other validators?

2022-08-16 15:36 UTC, tristen commented on src/components/control-file/control-file.tsx
> +  themeControlWrapper: PropTypes.string
Ah! good catch `themeControlFileClear` is no longer relevant so I've removed it and indicated its now dropped in the changelog.

2022-08-16 15:42 UTC, tristen commented on src/components/copy-button/copy-button.tsx
> +import React, { ReactElement, useState, useEffect, HTMLAttributes} from 'react';
🤔 I'm not reproducing this in Chrome!

![copy](https://user-images.githubusercontent.com/61150/184921386-cafd33db-d7b4-48e4-b09c-e272081a416f.gif)

@miafan23 are there any repeatable steps?

2022-08-16 16:49 UTC, tristen commented on src/components/copy-button/copy-button.tsx
> +import React, { ReactElement, useState, useEffect, HTMLAttributes} from 'react';
Ah! I _am_ repeating if the application performs a live reload. If I just reload the page on my own, things work as expected. Is that true for you as well?

2022-08-17 08:18 UTC, miafan23 commented on src/components/copy-button/copy-button.tsx
> +import React, { ReactElement, useState, useEffect, HTMLAttributes} from 'react';
It seems not related to the live reload. It does not work after I copied successfully a couple of or even two times.
Reproduce step:
1. Copy first example of copiable
2. Copy second example of copiable 
3. Copy example 1 again and then it does work

https://user-images.githubusercontent.com/9078950/185069780-d3ab1178-cbe7-4a93-a9e0-ca06def08130.mp4

2022-08-17 08:22 UTC, miafan23 commented on src/components/control-file/control-file.tsx
> +  themeControlWrapper: PropTypes.string
I also found that these rewritten components are missing the default value in the document. Are they removed intentionally? 
This is original document:
<img width="968" alt="Screen Shot 2022-08-17 at 11 21 39" src="https://user-images.githubusercontent.com/9078950/185070762-7e18e253-0024-4230-a4d5-5ffb138db3a0.png">
This is current document:
<img width="974" alt="Screen Shot 2022-08-17 at 11 22 22" src="https://user-images.githubusercontent.com/9078950/185070882-7a34b32d-731e-4aaa-b851-20c66bc65549.png">

2022-08-17 15:53 UTC, tristen commented on src/components/control-file/control-file.tsx
> +  themeControlWrapper: PropTypes.string
@miafan23 yeah, that's one of the shortcomings of using react docgen and dropping `static defaultProps` from components. What do you think about just manually writing them into the descriptions instead?

2022-08-17 15:54 UTC, tristen commented on src/components/copy-button/copy-button.tsx
> +import React, { ReactElement, useState, useEffect, HTMLAttributes} from 'react';
@miafan23 Thanks again for this catch. I _think_ I've addressed it by reinitializing the copy button with the same ref element each time

2022-08-18 09:21 UTC, miafan23 commented on src/components/control-file/control-file.tsx
> +  themeControlWrapper: PropTypes.string
Yeah, I think it's OK to manually write default values if auto-generating is impossible.

2022-08-18 10:11 UTC, miafan23 commented on src/components/copy-button/copy-button.tsx
> +import React, { ReactElement, useState, useEffect, HTMLAttributes} from 'react';
Works now 🥳! Even though I don't not get the reason why it was not working if the clicked button was the ref.

2022-08-18 10:11 UTC, miafan23 approved these changes

2022-08-18 14:21 UTC, tristen commented on src/components/copy-button/copy-button.tsx
> +import React, { ReactElement, useState, useEffect, HTMLAttributes} from 'react';
I might look into testing this a bit better : /

2022-08-18 15:59 UTC, tristen commented on src/components/control-file/control-file.tsx
> +  themeControlWrapper: PropTypes.string
oh! I figured out a way to do this that preserves the default value parsing! I can destructure the props in the component function as well as declare `props` for that `const extraProps = omit(props, propNames);` variable I need.

2022-08-18 17:21 UTC, merged