Rewrite radio/checkbox components
mapbox/mr-ui pull request #196
Opened 2022-08-19 01:05 UTC by tristen

Similar to #195, I've taken a simpler approach to these by rewriting to use TypeScript + React testing library. One change to note is the styling differences to the `ControlToggleGroup` which keeps more in line with its styling/heirarchy in practice

--- 

Closes #187 
Closes #16

2022-08-23 12:28 UTC, miafan23 requested changes
It looks great!
One minor user experience suggestion: It might be better if the cursor is "hand" when it is hovering on the label as the label is clickable too. 

https://user-images.githubusercontent.com/9078950/186157852-fdf82e69-b56b-40d6-acb3-aa9a707c1485.mp4

2022-08-23 12:28 UTC, miafan23 commented on src/components/control-checkbox-set/control-checkbox-set.tsx
> +    const isActive = value.indexOf(d.value) >= 0 ? true : false;
```suggestion
    const isActive = value.includes(value);
```
Ternary expression is redundant here since the return of the function is already boolean

2022-08-23 13:34 UTC, tristen commented on src/components/control-checkbox-set/control-checkbox-set.tsx
> +  value: PropTypes.array,
Good catch! and an unecessary prop. I've removed it.

2022-08-24 08:31 UTC, miafan23 approved these changes

2022-08-24 11:34 UTC, merged