Add context menu component
mapbox/mr-ui pull request #206
Opened 2023-03-15 00:00 UTC by tristen

Adds a context menu component powered by the [API provided in Radix](https://www.radix-ui.com/docs/primitives/components/context-menu#api-reference).

2023-03-15 14:31 UTC, tristen commented
Just flagging that the diff of changes looks big on account of snapshots changing with radix package updates. The implementation of the context menu + tests is like half of it.

2023-03-15 19:31 UTC, VLuisa commented on src/components/context-menu/context-menu.tsx
> +  keyCode?: string;
Would we expect someone to use the `<KeybindingTooltipWrapper />` with this in Studio? Or is that redundant?

2023-03-15 19:33 UTC, VLuisa commented on src/components/context-menu/context-menu.tsx
> +  themeControlWrapper = 'bg-white round shadow-darken10 px6 py6 txt-s wmin240',
Nitpick: For the default values, the `shadow-darken10` feels odd on the disabled line item b/c it hints at interactivity that's not available

2023-03-15 19:34 UTC, VLuisa commented on src/components/context-menu/context-menu.tsx
> +  themeSeparator = 'border-t border--gray-light my6'
having this in the api is nice 👍

2023-03-15 19:37 UTC, VLuisa commented on src/components/context-menu/context-menu.tsx
> +  themeControlWrapper = 'bg-white round shadow-darken10 px6 py6 txt-s wmin240',
`txt-s` felt a bit small for the list item labels, what do you think about `txt-ms` instead?

2023-03-15 19:40 UTC, VLuisa commented on src/docs/index.js
> +import './miscellaneous.css';
What's this for?

2023-03-15 19:41 UTC, VLuisa commented on src/docs/index.js
> +import './miscellaneous.css';
Oh duh, scrolling down to the actual file 😅

2023-03-15 19:48 UTC, VLuisa commented on src/components/context-menu/context-menu.tsx
> +   * Each object contain two fields:
```suggestion
   * Each object contains two fields:
```
typo

2023-03-15 19:49 UTC, VLuisa requested changes
This is really exciting! I think the overall style looks great for use in Studio and I like the flexibility for styling you're providing in the api. Left a few small comments for your thoughts.

2023-03-15 20:24 UTC, tristen commented on src/components/context-menu/context-menu.tsx
> +  keyCode?: string;
ohhh that's a great call! so instead os a string this should accept a `ReactNode`?

2023-03-15 20:25 UTC, tristen commented on src/docs/index.js
> +import './miscellaneous.css';
It is ... It _might_ actually be worth adding these specific rules to mbx-assembly instead 🤔

2023-03-15 20:28 UTC, tristen commented on src/components/context-menu/context-menu.tsx
> +  themeControlWrapper = 'bg-white round shadow-darken10 px6 py6 txt-s wmin240',
> Nitpick: For the default values, the `shadow-darken10` feels odd on the disabled line item b/c it hints at interactivity that's not available

I'm not sure I understand this one. Could you share a screenshot?

2023-03-15 20:39 UTC, VLuisa commented on src/components/context-menu/context-menu.tsx
> +  themeControlWrapper = 'bg-white round shadow-darken10 px6 py6 txt-s wmin240',
@tristen yep! I don't think the disabled item should have a background color on hover
<img width="360" alt="image" src="https://user-images.githubusercontent.com/10137547/225436498-6d589005-550f-414a-8c1c-53b6e4dcbae5.png">

2023-03-15 20:48 UTC, VLuisa commented on src/components/context-menu/context-menu.tsx
> +  keyCode?: string;
probably? may be something we have to play with as we implement it in Studio.

2023-03-15 20:49 UTC, VLuisa commented on src/docs/index.js
> +import './miscellaneous.css';
could be! are they reusable in other components for focus states?

2023-03-17 17:22 UTC, samanpwbb commented
Wow

2023-03-21 16:27 UTC, VLuisa approved these changes
LGTM!

2023-03-22 16:57 UTC, merged