Support react@18
mapbox/mr-ui pull request #220
Opened 2024-03-18 10:13 UTC by miafan23

2024-03-22 13:38 UTC, tristen requested changes
@miafan23 left a couple of questions! Could you fill out the description of this PR for our future selves? It would be good to know about the necessity of this change, the Jira ticket this is references and the change to `react-submittable`.

2024-03-22 13:38 UTC, tristen commented on src/components/accordion/__snapshots__/accordion.test.tsx.snap
What's up with these weird snapshot changes?

2024-03-22 13:38 UTC, tristen commented on src/components/utils/use_previous.test.ts
Good to know this has been consolidated into the latest version of `@testing-library/react`!

2024-03-22 13:38 UTC, tristen commented on package.json
> +    "@mapbox/react-submittable": "^2.1.0-alpha.0",
What changes happened here besides the new package name? It's not great adding an `alpha` dependency if we don't need to.

2024-03-22 13:38 UTC, tristen commented on package.json
> +  "version": "3.0.0",
Why is this a major version bump if it still supports `16`?

2024-03-22 15:27 UTC, miafan23 commented on src/components/accordion/__snapshots__/accordion.test.tsx.snap
Radix changed the id for React 18 for better support of SSR
https://github.com/radix-ui/primitives/blob/main/packages/react/id/src/id.tsx#L10
https://www.radix-ui.com/primitives/docs/guides/server-side-rendering

2024-03-22 15:36 UTC, miafan23 commented on package.json
> +    "@mapbox/react-submittable": "^2.1.0-alpha.0",
Oh, I am just waiting for https://github.com/mapbox/react-submittable/pull/9 to be merged and released

2024-03-25 08:17 UTC, miafan23 commented
>the Jira ticket this is references

@tristen  This is a public repo, I am not sure if we should refer jira ticket here 🤔

2024-03-26 08:29 UTC, miafan23 commented on src/components/tabs/tabs.test.tsx
> +        })
These tests sometime failed

2024-03-26 14:07 UTC, tristen approved these changes

2024-03-27 08:40 UTC, merged